# vela-app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: test-app
      type: webservice
      properties:
        image: oamdev/hello-world:v2
        port: 8000